### ISSUE TITLE
时空洞窟已持有強化過的加護

### ISSUE THREAD

**Issue by jiaoxiaohang** [moonheart/mementomori-helper#14]
[2023-10-04 11:47:41] 当前第 3层，坐标 0,7，状态 Selected, BattleAndRelicReinforce 敌人战斗力 29112496
[2023-10-04 11:47:42] https://prd1-ap2-api.mememori-boi.com/api/dungeonBattle/rewardBattleReinforceRelic
[2023-10-04 11:47:42] 已持有強化過的加護。
[2023-10-04 11:47:42] {"DungeonGridGuid":"ffd7621a24f8462084301456e24b1f3e","SelectedRelicId":46,"CurrentTermId":18}
[2023-10-04 11:47:42] {"ErrorCode":122051,"Message":"","ErrorHandlingType":0,"ErrorMessageId":0,"MessageParams":null}
[2023-10-04 11:47:42] MementoMori.Exceptions.ApiErrorException: 已持有強化過的加護。
   at MementoMori.MementoNetworkManager.GetResponse[TReq,TResp](TReq req, Action`1 log, Action`1 userData) in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoNetworkManager.cs:line 242
   at MementoMori.MementoMoriFuncs.GetResponse[TReq,TResp](TReq req) in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoMoriFuncs.cs:line 521
   at MementoMori.MementoMoriFuncs.AutoDungeonBattle(Action`1 log, CancellationToken cancellationToken) in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoMoriFuncs.cs:line 411
   at MementoMori.MementoMoriFuncs.<AutoDungeonBattle>b__107_0(Action`1 log, CancellationToken token) in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoMoriFuncs.Ops.cs:line 793
   at MementoMori.MementoMoriFuncs.<ExecuteQuickAction>b__90_0() in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoMoriFuncs.Ops.cs:line 150

**Comment by moonheart** [comment]
已在新版中尝试解决

**Comment by jiaoxiaohang** [comment]
> 已在新版中尝试解决

新版启动进入网页报错

![image](https://github.com/moonheart/mementomori-helper/assets/69664925/e3d3448b-d067-4526-93a6-19b8261c3014)

**Comment by moonheart** [comment]
下载的是 dev 还是 1.0.2? 建议用 1.0.2 的
