### ISSUE TITLE
Sync User Info Failure

### ISSUE THREAD

**Issue by ParadoxChains** [moonheart/mementomori-helper#29]
Sync User Info results in an exception. Web front end provides this error message at the bottom: "An error has occurred. This application may no longer respond until reloaded. [Reload](http://localhost:5000/)"

Windows 11 error:
`warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Please Click Login to Use Assistant
      System.InvalidOperationException: Please Click Login to Use Assistant
         at MementoMori.MementoNetworkManager.GetResponse[TReq,TResp](TReq req, Action`1 log, Action`1 userData)
         at MementoMori.MementoMoriFuncs.GetResponse[TReq,TResp](TReq req)
         at MementoMori.MementoMoriFuncs.UserGetUserData()
         at MementoMori.MementoMoriFuncs.SyncUserData()
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'tpsisPMUUvDlvVCpND5oZB3lLCp1kN7aqPqq6rsvipo'.
      System.InvalidOperationException: Please Click Login to Use Assistant
         at MementoMori.MementoNetworkManager.GetResponse[TReq,TResp](TReq req, Action`1 log, Action`1 userData)
         at MementoMori.MementoMoriFuncs.GetResponse[TReq,TResp](TReq req)
         at MementoMori.MementoMoriFuncs.UserGetUserData()
         at MementoMori.MementoMoriFuncs.SyncUserData()
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
`

**Comment by moonheart** [comment]
Did you login your account?

**Comment by ParadoxChains** [comment]
Pretty sure I did, but can not repro issue again, might be user error.
